
StockAnalyzer v2

Runs on fe west 1 at 

https://stockanalyzerv2.west-1.fe.gopivotal.com/index





This was original basis for this application:

== Building

Build the app with the following command:

[source,bash]
----
$ ./gradlew assemble
----

== Running on Cloud Foundry

Before pushing the app, create a MySQL database service as either a managed service instance or user-provided service instance. The name of the service instance must be `StockAnalyzerDb` to match the property names in the XML configuration. If creating a user-provided service instance, the credentials should be formed as followed:

Then push the app to CF:

[source,bash]
----
$ cf push
----

Then browse to the app's route to see the data stored in the database.

The three configuration options listed above are selected by Spring profiles. To enable one of the profiles,

[source,bash]
----
$ cf set-env spring-cloud-connectors-xml SPRING_PROFILES_ACTIVE {profile name}
$ cf restage spring-cloud-connectors-xml
----

where `{profile name}` is one of `auto`, `cloud-properties`, or `boot-properties` corresponding to the three configuration approaches listed above.

